# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imagem3.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import pathlib

from PyQt5 import QtCore, QtGui, QtWidgets
import arqTeste
import arqImagem


class Ui_MainWindow(object):
    caminho = ''

    def checar(self):
        vetor = arqImagem.conectar(self.caminho)
        texto = f'PLACA: {vetor[0]}\nMARCA: {vetor[1]}\nCOR: {vetor[2]}' \
                f'\nUF: {vetor[3]}\nMunicipio: {vetor[4]}'
        self.informacoes.setText(texto)

    def _open_file_dialog(self): # a function to open the dialog window
        result = str(QtWidgets.QFileDialog.getOpenFileName()[0])
        self.caminho = result
        return result

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(713, 441)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 20, 71, 21))
        self.label.setObjectName("label")
        self.pesquisar = QtWidgets.QPushButton(self.frame)
        self.pesquisar.setGeometry(QtCore.QRect(190, 60, 75, 23))
        self.pesquisar.setObjectName("pesquisar")
        self.informacoes = QtWidgets.QLabel(self.frame)
        self.informacoes.setGeometry(QtCore.QRect(370, 30, 291, 361))
        self.informacoes.setText("")
        self.informacoes.setObjectName("informacoes")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(90, 20, 171, 23))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.frame)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # funcao
        self.pesquisar.clicked.connect(self.checar)
        self.retranslateUi(MainWindow)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        #self.pushButton.clicked.connect(self.get_image)
        directory = self.pushButton.clicked.connect(self._open_file_dialog)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "IMAGEM: "))
        self.pesquisar.setText(_translate("MainWindow", "PESQUISAR"))
        self.pushButton.setText(_translate("MainWindow", "imagem"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
